// Part of FoundationKit http://foundationk.it
// 
// thanks to Kendall Helmstetter Geln
// http://stackoverflow.com/questions/2299841/objective-c-introspection-reflection

#import <Foundation/Foundation.h>

/**
 This category adds class-methods to NSObject that return an autogenerated description of an object,
 based on it's properties.
 */
@interface NSObject (FKDescription)

+ (NSString *)autogeneratedDescriptionOf:(id)instance classType:(Class)classType;
+ (NSString *)autogeneratedDescriptionOf:(id)instance;

@end
