// Part of FoundationKit http://foundationk.it
// 
// thanks to Kendall Helmstetter Geln
// http://stackoverflow.com/questions/2299841/objective-c-introspection-reflection

#import <Foundation/Foundation.h>

@interface NSObject (FKDescription)

+ (NSString *)autogeneratedDescriptionOf:(id)instance classType:(Class)classType;
+ (NSString *)autogeneratedDescriptionOf:(id)instance;

@end
